import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Script from "next/script";
export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>{`
        h2 {
          font-size: 38px;
        }
        h3 {
          font-size: 28px;
        }
      `}</style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://example.com/script.js" />

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className="Span">Hunting Coder</span>
        </h1>
        {/* <Image
          className={styles.myImg}
          src="/LogoImg.avif"
          alt="Logo"
          width={237}
          height={158}
        /> */}
        <p className={styles.description}>
          A blog for hunting coders by a hunting coder
        </p>

        <div class="blogs">
          <h2>Latest blogs</h2>
          <div class="blogItem">
            <h3>How to javascript in 2022?</h3>
            <p>
              It is a programming language used to design logic for web app.
            </p>
          </div>
          <div class="blogItem">
            <h3>How to javascript in 2022?</h3>
            <p>
              It is a programming language used to design logic for web app.
            </p>
          </div>
          <div class="blogItem">
            <h3>How to javascript in 2022?</h3>
            <p>
              It is a programming language used to design logic for web app.
            </p>
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}></footer> */}
    </div>
  );
}
