import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Script from "next/script";
import React, { useEffect, useState } from "react";
import Link from "next/link";
export default function Home(props) {
  const [data, setData] = useState(props.allBlogs);

  const HandleChange = ()=>{
  }
  return (
    <div className={styles.container}>
      <main className={styles.main}>
        {/* <style jsx>{`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}</style> */}
        <Head>
          <title>Hunting Coder</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Script src="https://example.com/script.js" />

        <Image
          className={styles.myImg}
          src="/LogoImg.avif"
          alt="Logo"
          width={237}
          height={158}
        />
        <h1 className={styles.title}>
          <span className="Span">{"<Hunting Coder/>"}</span>
        </h1>

        <div className="blogs">
          <h3 className={styles.blogItemh3}>Latest blogs</h3>
          {data.map((item, index) => {
            return (
              <div className="blogItem" key={index}>
                <h3>{item.title}?</h3>
                <p>{item.content.substr(0, 300)}...</p>
                <button className={styles.btn} onClick={HandleChange}>
                  <Link href={`/blogpost/${item.slug}`}>Read More</Link>
                </button>
              </div>
            );
          })}
        </div>
        {/* <footer className={styles.footer}></footer> */}
      </main>
    </div>
  );
}
export async function getServerSideProps(context) {
  let data = await fetch("http://localhost:3000/api/blogs");
  let allBlogs = await data.json();

  return {
    props: { allBlogs }, // will be passed to the page component as props
  };
}